### ISSUE TITLE
Connection refused IoT 33 Wifi

### ISSUE THREAD

**Issue by antonigimenezrodriguez** [mobizt/Firebase-Arduino-WiFiNINA#18]
Hi! I'm trying to connect to my Firebase Database with my Arduino nano IoT 33 Wifi and always gets "connection refused"

![imagen](https://user-images.githubusercontent.com/74731165/118235206-bcc33000-b494-11eb-9adc-a6a471f84a9f.png)

I try with desktop IDE and arduino IoT cloud and always gets "connection refused".

I use the example code and the rules are read/write: true.
I don't know why is wrong

**Comment by mobizt** [comment]
1. You should  try to update WiFiNINA firmware first by follow [this](https://www.arduino.cc/en/Tutorial/WiFiNINA-FirmwareUpdater).

2. The FIREBASE_HOST may not valid.

This credential will be used as part of internal request URL end point which device can't find the server or URL or server reject the connection due to not found.

The FIREBASE_HOST should defined as <databaseName>.firebaseio.com or <databaseName>.<region>.firebasedatabase.app

This URL should be copied from the Firebase RTDB console, see the URL at the top of database tree, copy it by excluding the https:// at the beginning and / (slash) at the end.

3. Try to renew the database secret.

**Comment by antonigimenezrodriguez** [comment]
Step 1: done (Version 1.3.0 of WiFi NINA)

![imagen](https://user-images.githubusercontent.com/74731165/118238873-686e7f00-b499-11eb-8c39-6f36fa060e02.png)


Step 2: I copy the DB URL from that:

![imagen](https://user-images.githubusercontent.com/74731165/118238653-162d5e00-b499-11eb-8b4e-afa9d743a7f4.png)

And secret from that:

![imagen](https://user-images.githubusercontent.com/74731165/118238812-5987cc80-b499-11eb-976d-c1fa39334651.png)

Step 3: done

I generate the last secret today, with same result

![imagen](https://user-images.githubusercontent.com/74731165/118239076-9c49a480-b499-11eb-8da4-dde2b713a25e.png)

**Comment by mobizt** [comment]
Don't forget to add your firebase domain and update certificate.

Try following

Reset your router or connect trough the mobile or PC mobile hotspot.

Change the USB cable with shorter cable or try to connect the large value capacitor between 3.3V and GND.

Go to Arduino IDE choose File -> Examples -> WiFiNINA -> WiFiSSLClient and test it.

If the example works, the library should work too.

**Comment by antonigimenezrodriguez** [comment]
Yeah! I update the domain certificate and it works!!!

Thx a lot!!!! 

I was desperate

![imagen](https://user-images.githubusercontent.com/74731165/118241447-6fe35780-b49c-11eb-9944-11c3520eb87d.png)

**Comment by AdleeAfif** [comment]
> Yeah! I update the domain certificate and it works!!!
> 
> Thx a lot!!!!
> 
> I was desperate
> 
> ![imagen](https://user-images.githubusercontent.com/74731165/118241447-6fe35780-b49c-11eb-9944-11c3520eb87d.png)

hello, may i know how did you update your certificate? i'm doing my project last night and it suddenly refused to send any data to firebase..
