### ISSUE TITLE
HELP Multi path stream

### ISSUE THREAD

**Issue by ayyysh04** [mobizt/Firebase-Arduino-WiFiNINA#22]
can we do multi path streaming like in esp8266 in arduino rev 2??

**Comment by mobizt** [comment]
Arduino UNO WiFi Rev.2 has only 6,144 bytes memory and it is avr platform unlike SAMD which is arm which support fully C++ 
Then it is not suitable to use in this kind of application.

This library can be supported more features as in ESP32 and ESP8266 Firebase library if I cut this UNO WiFi Rev. 2 but it will break  the API at all.

Then it's not suitable to implement because of low memory and lack of dynamic memory allocation in C++ supported by avr platform which required for database operaton.
