### ISSUE TITLE
Can't set data reason: Connection Refused

### ISSUE THREAD

**Issue by onlineworke** [mobizt/Firebase-Arduino-WiFiNINA#26]
I can not set data to firebase from Arduino Nano Iot 33. It was working perfectly before and the code is working 100% fine as I have tested it before and it was working fine but suddenly it has started to give an error "can't set data REASON: connection refused". I have a connection to internet and it works fine as it say Connected with IP: xxx.xxx.x.xx. I have tested the connection to same database from esp8266 and it works fine as well. I have added all the details correctly and this same code was working perfectly fine before. Your help in this matter will highly be appreciated!

**Comment by mobizt** [comment]
You should update Firmware and certificate.

Read issue #18

**Comment by mobizt** [comment]
When you buy this Arduino module which used the [u-blox NINA W-102](https://www.u-blox.com/en/product/nina-w10-series-open-cpu) WIFI module which is ESP32 inside that WiFi module, **you need to setup it before used** by update firmware and SSL certificates of servers that you want to connect with.

The firmware may be already loaded by the seller since you bough it, but the WiFiNINA firmware from Arduino team always require the SSL verification when connecting to secure port.  The server's SSL certificate that used for verification is Root certificate which it is valid for years e.g. 15 or 20 years.  

And you need to update it when you've found the error connection refused which is because the certificate was expired or Google changes (install new) the certificate or renew certificate.
