### ISSUE TITLE
Can't get examples to execute

### ISSUE THREAD

**Issue by oserani** [mobizt/Firebase-Arduino-WiFiNINA#45]
Hi there - trying to run the basic examples to run but I keep getting error 5 (Connection Refused) consistently.  No matter what I do.

I am using the following for the database URL
#define DATABASE_URL "poolmonitor-b661a-default-rtdb.firebaseio.com" //<databaseName>.firebaseio.com or <databaseName>.<region>.firebasedatabase.app
and the database secret provided by google.

Wifi connects just fine, but I am struggling with getting a connection to firebase

**Comment by mobizt** [comment]
See https://github.com/mobizt/Firebase-Arduino-WiFiNINA/issues/18

**Comment by oserani** [comment]
Thanks!  Renewing the "secret" seemed to do it.  Do we have to worry about the "deprecation" of database secrets comment on the firebase console.  Thanks again!

**Comment by mobizt** [comment]
The database secret is obsoleted for years.

I hope Google will not revoke this database access method. If this method was revoked, some Google services may not be able to access the Firebase RTDB.

I cannot add Authentication support for this library as in my [other Firebase libraries](https://github.com/mobizt/Firebase-ESP-Client) because the limited memory and flash space of AVR based Arduino UNO WiFi Rev2.

**Comment by oserani** [comment]
Gotcha. I’m a total newbie, but I have a raspberry pico w stashed somewhere.  Maybe one day I’ll try it on that.  Thanks again OrlandoOn Apr 19, 2023, at 21:19, Suwatchai K. ***@***.***> wrote:﻿
The database secret is obsoleted for years.
I hope Google will not revoke this database access method. If this method was revoked, some Google services may not be able to access the Firebase RTDB.
I cannot add Authentication support for this library as in my other Firebase libraries because the limited memory and flash space of AVR based Arduino UNO WiFi Rev2.
